# Generated by Django 4.1.2 on 2022-12-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received_by',
        ),
    ]
