# Generated by Django 4.1.2 on 2023-01-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroimage",
            name="hero_image",
            field=models.ImageField(default="default.jpg", upload_to="hero/%Y-%m-%d"),
        ),
    ]
