# Generated by Django 4.1.2 on 2022-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_visitor_about_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/%Y-%m-%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
