# Generated by Django 4.1.2 on 2022-12-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testmony/%Y-%m-%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Graphics', 'Graphics'), ('Photography', 'Photography'), ('Videography', 'Videography')], max_length=100),
        ),
    ]
