# Generated by Django 4.1.2 on 2022-12-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
